### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TaranVH**
Hambuger

### CODE REVIEW

**Comment by TaranVH** [comment]
Hamburgers.

**Comment by TaranVH** [comment]
wait, the branch can be DELETED!?
i guess the "main branch" has the changes that were made, but like... why .. what, why would you want to delete the branch? isn't the point of github to be able to look back though the history of how a repository was assembled?

**Comment by TaranVH** [comment]
this is the thing I am seeing:
image

**Comment by TaranVH** [comment]
I am going to delete this fucking branch just to see what happens.

**Comment by TaranVH** [comment]
well it looks like we're all still here, but I thought all this would vanish.

**Comment by TaranVH** [comment]
I'm gonna delete the fork after i figure out what the hell I actually just did. because it looks like nothing changed. 
image

**Comment by Jonta** [comment]
I think GitHub offers this as a cleanup thing

Scenario:

- **You see a spelling error in a piece of software**
- **You correct it**
- Doing so requires:
- Forking
- Correcting the spelling error
- Issuing a pull request
- The pull request being accepted
- **Now you're left with this whole repo on your account**

A lot of people would want to remove those, instead of their profiles being cluttered with hundreds of repos

If you remove "the fork" now, you would remove `TaranVH:patch-1`. The history of me merging this patch is still available in `Jonta:main`

Currently, your fork is still live: https://github.com/TaranVH/Taran-should-trash-this

**Edit:** My bad: You deleted the branch, not the fork

Re: Looks like nothing's changed: My guess is that your branch-dropdown-menu used to have "patch-1" listed. Branch dropdown has the word "main" between a branching symbol and a downward pointing arrow

And stuck close to the top of the viewport now it says "Jonta merged 1 commit into Jonta:main from TaranVH:patch-1 yesterday", where "TaranVH:patch-1" links to https://github.com/TaranVH/Taran-should-trash-this/tree/patch-1 - Which is 404, because you deleted that branch. =)

Clarification on why your fork wasn't deleted: My money's on this: You had already forked this project before issuing this pull-request. If you issue a pull-request to a project you haven't forked, GitHub would offer to delete your entire fork.

I keep the forks I make, to have a record, so I haven't played around with this

**Pull request merged**
